# Generated by Django 6.1.1 on 2026-09-25 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_import_legacy_tasks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete', 'priority', '-create', '-pk']},
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'High'), (2, 'Normal'), (3, 'Low')], default=2),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'complete'], name='task_user_complete_idx'),
        ),
    ]
