# Generated by Django 6.1.1 on 2026-09-25 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_authattemptbucket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('tr', 'Türkçe')], default='en', max_length=2)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('email_verified', models.BooleanField(default=False)),
                ('reminders', models.BooleanField(default=False)),
                ('reminder_hour', models.PositiveSmallIntegerField(default=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
