# Generated by Django 6.1.1 on 2026-09-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_deleted_at_task_recurrence_task_recurrence_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recurrence_created',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
