# Generated by Django 6.1.1 on 2026-09-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_recurrence_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='verified_email',
            field=models.EmailField(blank=True, default='', editable=False, max_length=254),
        ),
    ]
